"use client";

import { useState, useEffect, useCallback, useMemo } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { formatDate } from "@/lib/dates";
import { cn } from "@/lib/utils";
import {
  Plus,
  Copy,
  Trash2,
  Check,
  Download,
  ArrowRight,
  AlertTriangle,
  ChevronRight,
} from "lucide-react";

const AVAILABLE_SCOPES = ["telemetry", "policy", "govern"] as const;
type Scope = (typeof AVAILABLE_SCOPES)[number];

const KNOWN_SCOPES = new Set<string>(AVAILABLE_SCOPES);

const SCOPE_DESCRIPTIONS: Record<Scope, string> = {
  telemetry: "Push host telemetry to /api/v1/telemetry/*.",
  policy: "Sync deny-rules from /api/v1/policies/*.",
  govern: "Govern config + ungoverned + tamper events under /api/v1/govern/*.",
};

const BASE_URL = process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000";

/**
 * Mirror of `buildEnterpriseYaml` in
 * cortex/scaffold/mcp/src/cli/enterprise-setup.ts (rad 34-61).
 *
 * Output must be byte-for-byte equivalent (modulo the api_key value) so the
 * Setup Guide preview reflects exactly what the CLI writes.
 */
function buildEnterpriseConfigYaml(apiKey: string, baseUrl: string = BASE_URL) {
  const lines = [
    "# Cortex enterprise configuration. Generated by `cortex enterprise <key>`.",
    "# Single api_key is used for telemetry, policy, audit and govern services.",
    "enterprise:",
    `  api_key: ${apiKey}`,
    `  base_url: ${baseUrl}`,
    "",
    "telemetry:",
    "  enabled: true",
    "  interval_minutes: 1",
    "",
    "compliance:",
    "  frameworks: [iso27001, iso42001, soc2]",
    "  eu_addons: false",
    "",
    "govern:",
    "  mode: off",
    "  sync_on_startup: true",
    "  sync_interval_minutes: 60",
    "  tier_claude: prevent",
    "  tier_codex: prevent",
    "  tier_copilot: wrap",
    "  detect_ungoverned: true",
    "",
  ];
  return lines.join("\n");
}

type ApiKey = {
  id: string;
  name: string;
  keyPrefix: string;
  rawKey: string | null;
  scopes: string[];
  lastUsedAt: string | null;
  createdAt: string;
};

const STEP_PELLET =
  "flex items-center justify-center h-6 w-6 rounded-full text-xs font-bold bg-[hsl(var(--cortex-cyan))/0.12] text-[hsl(var(--cortex-cyan))] border border-[hsl(var(--cortex-cyan))/0.35]";

const CARD_TITLE =
  "text-sm font-medium tracking-wide uppercase text-[hsl(var(--cortex-fg-muted))]";

const CODE_BLOCK =
  "bg-[hsl(var(--cortex-surface-2))] border border-[hsl(var(--cortex-border))] rounded-lg px-4 py-3 text-sm text-[hsl(var(--cortex-fg))] font-mono";

export default function ApiKeysPage() {
  const [keys, setKeys] = useState<ApiKey[]>([]);
  const [newKeyName, setNewKeyName] = useState("");
  const [newKeyScopes, setNewKeyScopes] = useState<string[]>([
    "telemetry",
    "policy",
    "govern",
  ]);
  const [createdKey, setCreatedKey] = useState<string | null>(null);
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<ApiKey | null>(null);
  const [revoking, setRevoking] = useState(false);

  const fetchKeys = useCallback(async () => {
    const res = await fetch("/api/v1/api-keys");
    const data = await res.json();
    setKeys(data.keys ?? []);
    setLoading(false);
  }, []);

  useEffect(() => {
    fetchKeys();
  }, [fetchKeys]);

  const hasDeprecatedScope = useMemo(
    () => keys.some((k) => (k.scopes ?? []).some((s) => !KNOWN_SCOPES.has(s))),
    [keys]
  );

  const onboardKey = useMemo(() => {
    if (keys.length === 0) return "ctx_YOUR_KEY_HERE";
    return keys[0].rawKey ?? `${keys[0].keyPrefix}...`;
  }, [keys]);

  const previewYaml = useMemo(
    () => buildEnterpriseConfigYaml(onboardKey),
    [onboardKey]
  );

  const onboardCommand = `sudo cortex enterprise ${onboardKey}`;

  const createKey = async () => {
    setError(null);
    const res = await fetch("/api/v1/api-keys", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ name: newKeyName || "Default", scopes: newKeyScopes }),
    });

    if (!res.ok) {
      const data = await res.json();
      setError(data.error || "Failed to create key");
      return;
    }

    const data = await res.json();
    setCreatedKey(data.key.rawKey);
    setNewKeyName("");
    fetchKeys();
  };

  const confirmRevoke = async () => {
    if (!deleteTarget) return;
    setRevoking(true);
    try {
      await fetch(`/api/v1/api-keys/${deleteTarget.id}`, { method: "DELETE" });
      await fetchKeys();
    } finally {
      setRevoking(false);
      setDeleteTarget(null);
    }
  };

  const copyToClipboard = async (text: string, id: string) => {
    await navigator.clipboard.writeText(text);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  return (
    <div className="space-y-6 bg-[hsl(var(--cortex-bg))] text-[hsl(var(--cortex-fg))]">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight text-[hsl(var(--cortex-fg))]">
            Cortex access keys.
          </h1>
          <p className="text-sm text-[hsl(var(--cortex-fg-muted))] mt-1">
            Issued to hosts running cortex enterprise. One key per environment
            is recommended.
          </p>
        </div>

        <Button
          size="sm"
          onClick={() => {
            setCreatedKey(null);
            setError(null);
            setNewKeyName("");
            setNewKeyScopes(["telemetry", "policy", "govern"]);
            setDialogOpen(true);
          }}
        >
          <Plus className="h-4 w-4 mr-2" />
          Create Key
        </Button>
      </div>

      <Card className="cortex-card cortex-card-glow border-0">
        <CardHeader>
          <CardTitle className={CARD_TITLE}>Active Keys</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          {hasDeprecatedScope && (
            <div
              className="flex items-start gap-2 rounded-lg border px-3 py-2 text-sm bg-[hsl(var(--cortex-warn))/0.08] border-[hsl(var(--cortex-warn))/0.35] text-[hsl(var(--cortex-warn))]"
              role="status"
            >
              <AlertTriangle className="h-4 w-4 mt-0.5 shrink-0" />
              <span>
                One or more keys carry a deprecated scope (audit-log). They
                continue to work; rotate when convenient.
              </span>
            </div>
          )}

          {loading ? (
            <p className="text-sm text-[hsl(var(--cortex-fg-faint))]">
              Loading...
            </p>
          ) : keys.length === 0 ? (
            <p className="text-sm text-[hsl(var(--cortex-fg-faint))]">
              No API keys yet. Create one to connect cortex enterprise hosts.
            </p>
          ) : (
            <Table>
              <TableHeader>
                <TableRow className="border-[hsl(var(--cortex-border))]">
                  <TableHead className="text-[hsl(var(--cortex-fg-muted))]">
                    Name
                  </TableHead>
                  <TableHead className="text-[hsl(var(--cortex-fg-muted))]">
                    Key
                  </TableHead>
                  <TableHead className="text-[hsl(var(--cortex-fg-muted))]">
                    Scopes
                  </TableHead>
                  <TableHead className="text-[hsl(var(--cortex-fg-muted))]">
                    Last Used
                  </TableHead>
                  <TableHead className="text-[hsl(var(--cortex-fg-muted))]">
                    Created
                  </TableHead>
                  <TableHead />
                </TableRow>
              </TableHeader>
              <TableBody>
                {keys.map((key) => (
                  <TableRow
                    key={key.id}
                    className="border-[hsl(var(--cortex-border))]"
                  >
                    <TableCell className="text-[hsl(var(--cortex-fg))] font-medium">
                      {key.name}
                    </TableCell>
                    <TableCell>
                      <button
                        type="button"
                        onClick={() =>
                          copyToClipboard(key.rawKey ?? key.keyPrefix, key.id)
                        }
                        className="group flex items-center gap-1.5 cursor-pointer"
                      >
                        <span className="font-mono text-[hsl(var(--cortex-fg-faint))] text-xs break-all">
                          {key.rawKey ?? `${key.keyPrefix}...`}
                        </span>
                        {copiedId === key.id ? (
                          <Check className="h-3 w-3 text-[hsl(var(--cortex-ok))]" />
                        ) : (
                          <Copy className="h-3 w-3 text-[hsl(var(--cortex-fg-faint))] group-hover:text-[hsl(var(--cortex-fg-muted))] transition-colors" />
                        )}
                      </button>
                    </TableCell>
                    <TableCell>
                      <div className="flex flex-wrap gap-1 items-center">
                        {key.scopes?.map((s) => {
                          const isKnown = KNOWN_SCOPES.has(s);
                          return (
                            <span
                              key={s}
                              className="inline-flex items-center gap-1"
                            >
                              <Badge
                                variant="secondary"
                                className={cn(
                                  "text-xs",
                                  !isKnown && "line-through opacity-60"
                                )}
                                title={
                                  isKnown
                                    ? undefined
                                    : "Deprecated scope. Existing keys keep working; new keys can no longer request this scope."
                                }
                              >
                                {s}
                              </Badge>
                              {!isKnown && (
                                <span className="text-xs text-[hsl(var(--cortex-fg-faint))]">
                                  (deprecated)
                                </span>
                              )}
                            </span>
                          );
                        })}
                      </div>
                    </TableCell>
                    <TableCell className="text-sm text-[hsl(var(--cortex-fg-faint))]">
                      {key.lastUsedAt ? formatDate(key.lastUsedAt) : "Never"}
                    </TableCell>
                    <TableCell className="text-sm text-[hsl(var(--cortex-fg-faint))]">
                      {formatDate(key.createdAt)}
                    </TableCell>
                    <TableCell>
                      <Button
                        size="sm"
                        variant="ghost"
                        onClick={() => setDeleteTarget(key)}
                        className="text-[hsl(var(--cortex-fg-faint))] hover:text-[hsl(var(--cortex-alert))]"
                      >
                        <Trash2 className="h-4 w-4" />
                      </Button>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>

      <Card className="cortex-card cortex-card-glow border-0">
        <CardHeader>
          <CardTitle className={CARD_TITLE}>Setup Guide</CardTitle>
        </CardHeader>
        <CardContent className="space-y-6">
          {/* Step 1 — Install */}
          <div className="space-y-3">
            <div className="flex items-center gap-2">
              <span className={STEP_PELLET}>1</span>
              <span className="text-sm font-medium text-[hsl(var(--cortex-fg))]">
                Install
              </span>
            </div>
            <div className="ml-8 relative group">
              <pre className={cn(CODE_BLOCK, "pr-12")}>
                npm install -g @danielblomma/cortex-mcp
              </pre>
              <button
                type="button"
                onClick={() =>
                  copyToClipboard(
                    "npm install -g @danielblomma/cortex-mcp",
                    "install"
                  )
                }
                className="absolute top-2 right-2 p-1.5 rounded-md bg-[hsl(var(--cortex-surface-2))] border border-[hsl(var(--cortex-border))] opacity-0 group-hover:opacity-100 transition-opacity cursor-pointer"
              >
                {copiedId === "install" ? (
                  <Check className="h-3.5 w-3.5 text-[hsl(var(--cortex-ok))]" />
                ) : (
                  <Copy className="h-3.5 w-3.5 text-[hsl(var(--cortex-fg-muted))]" />
                )}
              </button>
            </div>
          </div>

          {/* Step 2 — Onboard host */}
          <div className="space-y-3">
            <div className="flex items-center gap-2">
              <span className={STEP_PELLET}>2</span>
              <span className="text-sm font-medium text-[hsl(var(--cortex-fg))]">
                Onboard host
              </span>
            </div>
            <div className="ml-8 space-y-2">
              <div className="relative group">
                <pre
                  className={cn(CODE_BLOCK, "pr-12")}
                  title="Writes managed-settings, hooks and starts the daemon. Requires sudo. Drops to your user after system writes."
                >
                  {onboardCommand}
                </pre>
                <button
                  type="button"
                  onClick={() => copyToClipboard(onboardCommand, "onboard")}
                  className="absolute top-2 right-2 p-1.5 rounded-md bg-[hsl(var(--cortex-surface-2))] border border-[hsl(var(--cortex-border))] opacity-0 group-hover:opacity-100 transition-opacity cursor-pointer"
                >
                  {copiedId === "onboard" ? (
                    <Check className="h-3.5 w-3.5 text-[hsl(var(--cortex-ok))]" />
                  ) : (
                    <Copy className="h-3.5 w-3.5 text-[hsl(var(--cortex-fg-muted))]" />
                  )}
                </button>
              </div>
              <p className="text-xs text-[hsl(var(--cortex-fg-muted))]">
                Writes managed-settings, hooks and starts the daemon. Requires
                sudo; drops to your user after system writes.
              </p>
            </div>
          </div>

          {/* Step 3 — What you get (YAML preview) */}
          <div className="space-y-3">
            <div className="flex items-center gap-2">
              <span className={STEP_PELLET}>3</span>
              <span className="text-sm font-medium text-[hsl(var(--cortex-fg))]">
                What you get
              </span>
            </div>
            <div className="ml-8 space-y-3">
              <p className="text-xs text-[hsl(var(--cortex-fg-muted))]">
                Read-only preview of the{" "}
                <code className="text-[hsl(var(--cortex-fg))] bg-[hsl(var(--cortex-surface-2))] px-1.5 py-0.5 rounded text-xs">
                  .context/enterprise.yml
                </code>{" "}
                the CLI writes for you.
              </p>
              <div className="relative group">
                <pre
                  className={cn(
                    CODE_BLOCK,
                    "pr-24 text-xs whitespace-pre overflow-x-auto"
                  )}
                >
                  {previewYaml}
                </pre>
                <div className="absolute top-2 right-2 flex gap-1">
                  <button
                    type="button"
                    onClick={() => void copyToClipboard(previewYaml, "yaml")}
                    className="p-1.5 rounded-md bg-[hsl(var(--cortex-surface-2))] border border-[hsl(var(--cortex-border))] opacity-0 group-hover:opacity-100 transition-opacity cursor-pointer"
                    title="Copy to clipboard"
                  >
                    {copiedId === "yaml" ? (
                      <Check className="h-3.5 w-3.5 text-[hsl(var(--cortex-ok))]" />
                    ) : (
                      <Copy className="h-3.5 w-3.5 text-[hsl(var(--cortex-fg-muted))]" />
                    )}
                  </button>
                  <button
                    type="button"
                    onClick={() => {
                      const yaml = `${previewYaml}\n`;
                      const blob = new Blob([yaml], { type: "text/yaml" });
                      const url = URL.createObjectURL(blob);
                      const a = document.createElement("a");
                      a.href = url;
                      a.download = "enterprise.yml";
                      a.click();
                      URL.revokeObjectURL(url);
                    }}
                    className="p-1.5 rounded-md bg-[hsl(var(--cortex-surface-2))] border border-[hsl(var(--cortex-border))] opacity-0 group-hover:opacity-100 transition-opacity cursor-pointer"
                    title="Download enterprise.yml"
                  >
                    <Download className="h-3.5 w-3.5 text-[hsl(var(--cortex-fg-muted))]" />
                  </button>
                </div>
              </div>
              {keys.length > 0 && !keys[0].rawKey && (
                <p className="text-xs text-[hsl(var(--cortex-fg-faint))]">
                  Showing prefix for{" "}
                  <span className="text-[hsl(var(--cortex-fg-muted))]">
                    {keys[0].name}
                  </span>
                  . The full key was shown once at creation.
                </p>
              )}
            </div>
          </div>

          {/* Step 4 — Verify */}
          <div className="space-y-3">
            <div className="flex items-center gap-2">
              <span className={STEP_PELLET}>4</span>
              <span className="text-sm font-medium text-[hsl(var(--cortex-fg))]">
                Verify
              </span>
            </div>
            <div className="ml-8 space-y-3">
              <div className="relative group">
                <pre className={cn(CODE_BLOCK, "pr-12")}>
                  cortex enterprise status
                </pre>
                <button
                  type="button"
                  onClick={() =>
                    copyToClipboard("cortex enterprise status", "verify")
                  }
                  className="absolute top-2 right-2 p-1.5 rounded-md bg-[hsl(var(--cortex-surface-2))] border border-[hsl(var(--cortex-border))] opacity-0 group-hover:opacity-100 transition-opacity cursor-pointer"
                >
                  {copiedId === "verify" ? (
                    <Check className="h-3.5 w-3.5 text-[hsl(var(--cortex-ok))]" />
                  ) : (
                    <Copy className="h-3.5 w-3.5 text-[hsl(var(--cortex-fg-muted))]" />
                  )}
                </button>
              </div>
              <div className="relative group">
                <pre className={cn(CODE_BLOCK, "pr-12 text-xs")}>
                  cortex enterprise status --json
                </pre>
                <button
                  type="button"
                  onClick={() =>
                    copyToClipboard(
                      "cortex enterprise status --json",
                      "verify-json"
                    )
                  }
                  className="absolute top-2 right-2 p-1.5 rounded-md bg-[hsl(var(--cortex-surface-2))] border border-[hsl(var(--cortex-border))] opacity-0 group-hover:opacity-100 transition-opacity cursor-pointer"
                >
                  {copiedId === "verify-json" ? (
                    <Check className="h-3.5 w-3.5 text-[hsl(var(--cortex-ok))]" />
                  ) : (
                    <Copy className="h-3.5 w-3.5 text-[hsl(var(--cortex-fg-muted))]" />
                  )}
                </button>
              </div>
              <p className="text-xs text-[hsl(var(--cortex-fg-muted))]">
                Look for{" "}
                <code className="text-[hsl(var(--cortex-fg))] bg-[hsl(var(--cortex-surface-2))] px-1 py-0.5 rounded">
                  Mode: advisory
                </code>{" "}
                or{" "}
                <code className="text-[hsl(var(--cortex-fg))] bg-[hsl(var(--cortex-surface-2))] px-1 py-0.5 rounded">
                  Mode: enforced
                </code>
                , one row per AI CLI on the host, and{" "}
                <code className="text-[hsl(var(--cortex-fg))] bg-[hsl(var(--cortex-surface-2))] px-1 py-0.5 rounded">
                  0
                </code>{" "}
                ungoverned/tamper events.
              </p>
              <a
                href="https://github.com/danielblomma/cortex/blob/main/docs/govern/README.md"
                target="_blank"
                rel="noreferrer noopener"
                className="inline-flex items-center gap-1 text-xs text-[hsl(var(--cortex-cyan))] hover:underline"
              >
                Read the operator manual
                <ArrowRight className="h-3 w-3" />
              </a>
            </div>
          </div>

          {/* Step 5 — Where to look */}
          <div className="space-y-3">
            <div className="flex items-center gap-2">
              <span className={STEP_PELLET}>5</span>
              <span className="text-sm font-medium text-[hsl(var(--cortex-fg))]">
                Where to look
              </span>
            </div>
            <div className="ml-8 grid grid-cols-1 md:grid-cols-3 gap-3">
              {[
                {
                  href: "/dashboard/govern",
                  title: "Govern.",
                  body: "Live system status, alerts, compliance.",
                },
                {
                  href: "/dashboard/audit",
                  title: "Audit.",
                  body: "Immutable trail of every AI action.",
                },
                {
                  href: "/dashboard/policies",
                  title: "Policies.",
                  body: "The deny-rules cortex enforces on this org.",
                },
              ].map((card) => (
                <a
                  key={card.href}
                  href={card.href}
                  className="cortex-card p-4 hover:border-[hsl(var(--cortex-cyan))] transition-colors group flex flex-col gap-2"
                >
                  <div className="flex items-center justify-between">
                    <span className="text-sm font-medium text-[hsl(var(--cortex-fg))]">
                      {card.title}
                    </span>
                    <ArrowRight className="h-4 w-4 text-[hsl(var(--cortex-fg-faint))] group-hover:text-[hsl(var(--cortex-cyan))] transition-colors" />
                  </div>
                  <span className="text-xs text-[hsl(var(--cortex-fg-muted))]">
                    {card.body}
                  </span>
                </a>
              ))}
            </div>
          </div>

          {/* Advanced / community fallback */}
          <details className="ml-0 group rounded-lg border border-[hsl(var(--cortex-border))] bg-[hsl(var(--cortex-surface-2))/0.5]">
            <summary className="cursor-pointer list-none flex items-center gap-2 px-4 py-3 text-xs uppercase tracking-wide text-[hsl(var(--cortex-fg-muted))]">
              <ChevronRight className="h-3.5 w-3.5 transition-transform group-open:rotate-90" />
              Advanced / community fallback
            </summary>
            <div className="px-4 pb-4 pt-1 space-y-2">
              <p className="text-xs text-[hsl(var(--cortex-fg-muted))]">
                Greenfield repos still need a{" "}
                <code className="text-[hsl(var(--cortex-fg))] bg-[hsl(var(--cortex-surface-2))] px-1 py-0.5 rounded">
                  .context/
                </code>{" "}
                directory before{" "}
                <code className="text-[hsl(var(--cortex-fg))] bg-[hsl(var(--cortex-surface-2))] px-1 py-0.5 rounded">
                  cortex enterprise
                </code>{" "}
                can write its config. Community users without an enterprise key
                stop here.
              </p>
              <div className="relative group/cmd">
                <pre className={cn(CODE_BLOCK, "pr-12 text-xs")}>
                  cd your-repo &amp;&amp; cortex init --bootstrap
                </pre>
                <button
                  type="button"
                  onClick={() =>
                    copyToClipboard(
                      "cd your-repo && cortex init --bootstrap",
                      "init"
                    )
                  }
                  className="absolute top-2 right-2 p-1.5 rounded-md bg-[hsl(var(--cortex-surface-2))] border border-[hsl(var(--cortex-border))] opacity-0 group-hover/cmd:opacity-100 transition-opacity cursor-pointer"
                >
                  {copiedId === "init" ? (
                    <Check className="h-3.5 w-3.5 text-[hsl(var(--cortex-ok))]" />
                  ) : (
                    <Copy className="h-3.5 w-3.5 text-[hsl(var(--cortex-fg-muted))]" />
                  )}
                </button>
              </div>
            </div>
          </details>
        </CardContent>
      </Card>

      {/* Create key dialog */}
      <Dialog
        open={dialogOpen}
        onOpenChange={(open) => {
          setDialogOpen(open);
          if (!open) {
            setCreatedKey(null);
            setError(null);
          }
        }}
      >
        <DialogContent className="bg-[hsl(var(--cortex-surface))] border-[hsl(var(--cortex-border))]">
          <DialogHeader>
            <DialogTitle className="text-[hsl(var(--cortex-fg))]">
              {createdKey ? "Key Created" : "Create API Key"}
            </DialogTitle>
          </DialogHeader>

          {error && (
            <div className="rounded-lg border px-4 py-3 text-sm bg-[hsl(var(--cortex-alert))/0.1] border-[hsl(var(--cortex-alert))/0.35] text-[hsl(var(--cortex-alert))]">
              {error}
            </div>
          )}

          {createdKey ? (
            <div className="space-y-4">
              <p className="text-sm text-[hsl(var(--cortex-fg-muted))]">
                Your new API key is ready. You can copy it anytime from the
                key list.
              </p>
              <div className="flex items-center gap-2">
                <code className="flex-1 bg-[hsl(var(--cortex-surface-2))] border border-[hsl(var(--cortex-border))] rounded-lg px-3 py-2 text-sm text-[hsl(var(--cortex-running))] font-mono break-all">
                  {createdKey}
                </code>
                <Button
                  size="sm"
                  variant="outline"
                  onClick={() => copyToClipboard(createdKey, "created-key")}
                >
                  {copiedId === "created-key" ? (
                    <Check className="h-4 w-4" />
                  ) : (
                    <Copy className="h-4 w-4" />
                  )}
                </Button>
              </div>
              <p className="text-xs text-[hsl(var(--cortex-fg-faint))]">
                Or copy the full config for{" "}
                <code className="text-[hsl(var(--cortex-fg-muted))]">
                  .context/enterprise.yml
                </code>
                :
              </p>
              <div className="relative group">
                <pre
                  className={cn(
                    CODE_BLOCK,
                    "pr-12 text-xs whitespace-pre overflow-x-auto"
                  )}
                >
                  {buildEnterpriseConfigYaml(createdKey)}
                </pre>
                <button
                  type="button"
                  onClick={() => {
                    const yaml = buildEnterpriseConfigYaml(createdKey);
                    void copyToClipboard(yaml, "created-yaml");
                  }}
                  className="absolute top-2 right-2 p-1.5 rounded-md bg-[hsl(var(--cortex-surface-2))] border border-[hsl(var(--cortex-border))] opacity-0 group-hover:opacity-100 transition-opacity cursor-pointer"
                >
                  {copiedId === "created-yaml" ? (
                    <Check className="h-3.5 w-3.5 text-[hsl(var(--cortex-ok))]" />
                  ) : (
                    <Copy className="h-3.5 w-3.5 text-[hsl(var(--cortex-fg-muted))]" />
                  )}
                </button>
              </div>
            </div>
          ) : (
            <div className="space-y-4">
              <Input
                placeholder="Key name (e.g., Production)"
                value={newKeyName}
                onChange={(e) => setNewKeyName(e.target.value)}
                className="bg-[hsl(var(--cortex-surface-2))] border-[hsl(var(--cortex-border))]"
              />
              <div>
                <p className="text-sm text-[hsl(var(--cortex-fg-muted))] mb-2">
                  Scopes
                </p>
                <div className="flex flex-col gap-2">
                  {AVAILABLE_SCOPES.map((scope) => {
                    const selected = newKeyScopes.includes(scope);
                    return (
                      <div key={scope} className="flex flex-col gap-1">
                        <button
                          type="button"
                          onClick={() =>
                            setNewKeyScopes((prev) =>
                              selected
                                ? prev.filter((s) => s !== scope)
                                : [...prev, scope]
                            )
                          }
                          className="cursor-pointer self-start"
                          title={SCOPE_DESCRIPTIONS[scope]}
                        >
                          <Badge
                            variant="outline"
                            className={cn(
                              "text-xs transition-colors",
                              selected
                                ? "text-[hsl(var(--cortex-fg))] border-[hsl(var(--cortex-cyan))/0.5] bg-[hsl(var(--cortex-cyan))/0.12]"
                                : "text-[hsl(var(--cortex-fg-faint))] border-[hsl(var(--cortex-border))] bg-[hsl(var(--cortex-surface-2))]"
                            )}
                          >
                            {selected && <Check className="mr-1 h-3 w-3" />}
                            {scope}
                          </Badge>
                        </button>
                        <p className="text-xs text-[hsl(var(--cortex-fg-faint))] ml-1">
                          {SCOPE_DESCRIPTIONS[scope]}
                        </p>
                      </div>
                    );
                  })}
                </div>
                <p className="text-xs text-[hsl(var(--cortex-fg-muted))] mt-3">
                  All three are required for the full Cortex Govern feature
                  set.
                </p>
              </div>
              <Button
                onClick={createKey}
                className="w-full"
                disabled={newKeyScopes.length === 0}
              >
                Generate Key
              </Button>
            </div>
          )}
        </DialogContent>
      </Dialog>

      {/* Revoke confirmation dialog */}
      <Dialog
        open={!!deleteTarget}
        onOpenChange={(open) => {
          if (!open) setDeleteTarget(null);
        }}
      >
        <DialogContent className="bg-[hsl(var(--cortex-surface))] border-[hsl(var(--cortex-border))] sm:max-w-md">
          <DialogHeader>
            <DialogTitle className="text-[hsl(var(--cortex-fg))]">
              Revoke API key?
            </DialogTitle>
            <DialogDescription className="text-[hsl(var(--cortex-fg-muted))]">
              This will permanently revoke{" "}
              <span className="font-medium text-[hsl(var(--cortex-fg))]">
                {deleteTarget?.name}
              </span>{" "}
              <span className="font-mono text-[hsl(var(--cortex-fg-faint))]">
                ({deleteTarget?.keyPrefix}...)
              </span>
              . Any instances using this key will lose access.
            </DialogDescription>
          </DialogHeader>
          <div className="flex justify-end gap-3 pt-2">
            <Button
              variant="outline"
              size="sm"
              onClick={() => setDeleteTarget(null)}
            >
              Cancel
            </Button>
            <Button
              size="sm"
              className="bg-[hsl(var(--cortex-alert))] hover:bg-[hsl(var(--cortex-alert))/0.85] text-white"
              onClick={() => void confirmRevoke()}
              disabled={revoking}
            >
              {revoking ? "Revoking..." : "Revoke Key"}
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
